require(ggplot2)
data("diamonds")
head(diamonds)
hist(diamonds$carat, main = "Carat_histogram", xlab = "Carat")
plot(price ~ carat, data = diamonds)
boxplot(diamonds$carat)
ggplot(data = diamonds) + geom_histogram(aes(x = carat))
ggplot(data = diamonds) + geom_density(aes(x = carat), fill = "grey50")
ggplot(diamonds, aes(x = carat, y = price)) + geom_point()
g <- ggplot(diamonds, aes(x = carat, y = price))
g + geom_point()
g + geom_point(aes(color = color))
g + geom_point(aes(color = color)) + facet_wrap(~color)
g + geom_point(aes(color = color)) + facet_grid(cut ~ clarity)
